format = """
$os\
$directory\
(\
[](fg:prev_bg bg:green)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
)\
(\
[](fg:prev_bg bg:yellow)\
$docker_context\
$package\
$c\
$cpp\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
[ ](bg:yellow)\
)\
$memory_usage\
$custom\
$sudo\
[](fg:prev_bg bg:bg)\
$fill\
$cmd_duration\
$time\
$username\
$hostname\
$line_break\
$jobs\
$battery\
$status\
$container\
$netns\
$shell\
$character
"""

###########
# primary #
###########

[os]
disabled = false
style = 'bg:bright-white fg:black'
format = '[ $symbol]($style)'

[directory]
style = "bg:blue fg:254 bold"
format = "[](fg:prev_bg bg:blue)[ $path ]($style)[$read_only]($read_only_style)"
read_only = "󰌾 "
read_only_style = "fg:red bg:blue"
# fish_style_pwd_dir_length = 1
# truncation_length  = 3
# truncation_symbol = "…/"

# git

[git_branch]
symbol = " "
style = "bg:green fg:black"
format = "[ $symbol$branch(:$remote_branch) ]($style)"

[git_commit]
style = "bg:green fg:black"
tag_symbol = "  "
format = '[\($hash$tag\) ]($style)'

[git_state]
style = "bg:green fg:black bold"
format = '[\($state( $progress_current/$progress_total\)) ]($style)'

# [git_metrics]
# added_style = "bg:green fg:black"
# deleted_style = "bg:green fg:red"

[git_status]
style = "bg:green fg:black bold"
format = '([$all_status$ahead_behind ]($style))'

#########
# right #
#########

[fill]
symbol=' '

[cmd_duration]
format = "[](bg:prev_bg fg:purple)[ $duration ]($style)"
style = "bg:purple fg:black"

[time]
# disabled = false
use_12hr = true
format = "[](bg:prev_bg fg:cyan)[ $time ]($style)"
style = "bg:cyan fg:black"
time_format = "%-I:%M %p"

[username]
# show_always = true
style_root = "bold fg:red bg:bright-black bold"
style_user = "fg:green bg:bright-black bold"
format = "[](bg:prev_bg fg:bright-black)[ $user ]($style)"

[hostname]
# ssh_only = false
# ssh_symbol = " "
ssh_symbol = "@"
style = "fg:yellow bg:bright-black"
format = "[@ $hostname ]($style)"

#########
# other #
#########

[shell]
disabled = true

[status]
symbol = " "

[sudo]
disabled = true
symbol = "󰩪 "

[memory_usage]
symbol = "󰍛 "
style = "bg:yellow fg:black" # lang background


#############
# languages #
#############

[aws]
symbol = " "
style = "bg:yellow fg:black" # lang background

[buf]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[bun]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[c]
format = '[ $symbol(\($name\) )]($style)'
symbol = " "
style = "bg:yellow fg:black" # lang background

[cmake]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[cobol]
format = "[ $symbol]($style)"
style = "bg:yellow fg:black" # lang background

[conda]
ignore_base = false
symbol = " "
style = "bg:yellow fg:black" # lang background

[cpp]
disabled = false
format = '[ $symbol(\($name\) )]($style)'
symbol = " "
style = "bg:yellow fg:black" # lang background

[crystal]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[daml]
format = "[ $symbol]($style)"
style = "bg:yellow fg:black" # lang background

[dart]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[deno]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[docker_context]
symbol = " "
style = "bg:yellow fg:black" # lang background

[dotnet]
format = "[ $symbol( $tfm )]($style)"
# format = "[ $symbol(󰓾 $tfm )]($style)"
# format = "[ $symbol(󰩷 $tfm )]($style)"
style = "bg:yellow fg:black" # lang background

[elixir]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[elm]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[erlang]
format = "[ $symbol]($style)"
style = "bg:yellow fg:black" # lang background

[fennel]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[fortran]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[fossil_branch]
symbol = " "
style = "bg:yellow fg:black" # lang background

[gcloud]
symbol = " "
style = "bg:yellow fg:black" # lang background

[gleam]
format = "[ $symbol]($style)"
style = "bg:yellow fg:black" # lang background

[golang]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[gradle]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[guix_shell]
symbol = " "
style = "bg:yellow fg:black" # lang background

[haskell]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[haxe]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[helm]
format = "[ $symbol]($style)"
style = "bg:yellow fg:black" # lang background

[hg_branch]
symbol = " "
style = "bg:yellow fg:black" # lang background

[java]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[julia]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[kotlin]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[lua]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[meson]
format = "[ $symbol]($style)"
symbol = "󰔷 "
style = "bg:yellow fg:black" # lang background

[mojo]
format = "[ $symbol]($style)"
style = "bg:yellow fg:black" # lang background

[nim]
format = "[ $symbol]($style)"
symbol = "󰆥 "
style = "bg:yellow fg:black" # lang background

[nix_shell]
symbol = " "
style = "bg:yellow fg:black" # lang background

[nodejs]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[ocaml]
format = "[ $symbol(\\($switch_indicator$switch_name\\))]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[odin]
format = "[ $symbol]($style)"
style = "bg:yellow fg:black" # lang background

[opa]
format = "[ $symbol]($style)"
style = "bg:yellow fg:black" # lang background

[package]
symbol = "󰏗 "
style = "bg:yellow fg:black" # lang background

[perl]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[php]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[pijul_channel]
symbol = " "
style = "bg:yellow fg:black" # lang background

[pixi]
format = "[ $symbol($environment)]($style)"
symbol = "󰏗 "
style = "bg:yellow fg:black" # lang background

[pulumi]
format = "[ $symbol$stack]($style)"
style = "bg:yellow fg:black" # lang background

[purescript]
format = "[ $symbol]($style)"
style = "bg:yellow fg:black" # lang background

[python]
format = "[ $symbol(\\($virtualenv\\) )]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[quarto]
format = "[ $symbol]($style)"
style = "bg:yellow fg:black" # lang background

[raku]
format = "[ $symbol]($style)"
style = "bg:yellow fg:black" # lang background

[red]
format = "[ $symbol]($style)"
style = "bg:yellow fg:black" # lang background

[rlang]
format = "[ $symbol]($style)"
symbol = "󰟔 "
style = "bg:yellow fg:black" # lang background

[ruby]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[rust]
format = "[ $symbol]($style)"
symbol = "󱘗 "
style = "bg:yellow fg:black" # lang background

[scala]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[solidity]
format = "[ $symbol]($style)"
style = "bg:yellow fg:black" # lang background

[swift]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[typst]
format = "[ $symbol]($style)"
style = "bg:yellow fg:black" # lang background

[vagrant]
format = "[ $symbol]($style)"
style = "bg:yellow fg:black" # lang background

[vlang]
format = "[ $symbol]($style)"
style = "bg:yellow fg:black" # lang background

[xmake]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[zig]
format = "[ $symbol]($style)"
symbol = " "
style = "bg:yellow fg:black" # lang background

[os.symbols]
AlmaLinux = " "
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
RockyLinux = " "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
