format = """
$os\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[ ](fg:prev_bg bg:bg)\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$netns\
$shell\
$character"""

###########
# primary #
###########

[os]
disabled = false
style = 'bg:white fg:black'
format = '[ $symbol]($style)'

[directory]
style = "bg:blue fg:254 bold"
format = "[](fg:prev_bg bg:blue)[ $path ]($style)[$read_only]($read_only_style)"
read_only = "󰌾 "
read_only_style = "fg:red bg:blue"

# git

[git_branch]
symbol = " "
style = "bg:green fg:black"
format = "[](fg:prev_bg bg:green)[ $symbol$branch(:$remote_branch) ]($style)"

[git_commit]
style = "bg:green fg:black"
tag_symbol = "  "

[git_state]
style = "bg:green fg:black"

# [git_metrics]
# added_style = "bg:green fg:black"
# deleted_style = "bg:green fg:red"

[git_status]
style = "bg:green fg:black"
format = '([$all_status$ahead_behind ]($style))'

# ssh

# [user]

[hostname]
ssh_symbol = " "

# time

# [cmd_duration]
#
# [time]
# disabled = true

#############
# languages #
#############

[aws]
symbol = " "

[buf]
format = "with [$symbol]($style)"
symbol = " "

[bun]
format = "via [$symbol]($style)"
symbol = " "

[c]
format = "via [$symbol($name)]($style)"
symbol = " "

[cmake]
format = "via [$symbol]($style)"
symbol = " "

[cobol]
format = "via [$symbol]($style)"

[conda]
ignore_base = false
symbol = " "

[cpp]
disabled = false
format = "via [$symbol($name)]($style)"
symbol = " "

[crystal]
format = "via [$symbol]($style)"
symbol = " "

[daml]
format = "via [$symbol]($style)"

[dart]
format = "via [$symbol]($style)"
symbol = " "

[deno]
format = "via [$symbol]($style)"
symbol = " "

[docker_context]
symbol = " "

[dotnet]
format = "[$symbol( $tfm )]($style)"
# format = "[$symbol(󰓾 $tfm )]($style)"
# format = "[$symbol(󰩷 $tfm )]($style)"

[elixir]
format = "via [$symbol]($style)"
symbol = " "

[elm]
format = "via [$symbol]($style)"
symbol = " "

[erlang]
format = "via [$symbol]($style)"

[fennel]
format = "via [$symbol]($style)"
symbol = " "

[fortran]
format = "via [$symbol]($style)"
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = " "

[gleam]
format = "via [$symbol]($style)"

[golang]
format = "via [$symbol]($style)"
symbol = " "

[gradle]
format = "via [$symbol]($style)"
symbol = " "

[guix_shell]
symbol = " "

[haskell]
format = "via [$symbol]($style)"
symbol = " "

[haxe]
format = "via [$symbol]($style)"
symbol = " "

[helm]
format = "via [$symbol]($style)"

[hg_branch]
symbol = " "

[java]
format = "via [$symbol]($style)"
symbol = " "

[julia]
format = "via [$symbol]($style)"
symbol = " "

[kotlin]
format = "via [$symbol]($style)"
symbol = " "

[lua]
format = "via [$symbol]($style)"
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
format = "via [$symbol]($style)"
symbol = "󰔷 "

[mojo]
format = "with [$symbol]($style)"

[nim]
format = "via [$symbol]($style)"
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
format = "via [$symbol]($style)"
symbol = " "

[ocaml]
format = "via [$symbol(\\($switch_indicator$switch_name\\) )]($style)"
symbol = " "

[odin]
format = "via [$symbol]($style)"

[opa]
format = "via [$symbol]($style)"

[package]
symbol = "󰏗 "

[perl]
format = "via [$symbol]($style)"
symbol = " "

[php]
format = "via [$symbol]($style)"
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
format = "via [$symbol($environment )]($style)"
symbol = "󰏗 "

[pulumi]
format = "via [$symbol$stack]($style)"

[purescript]
format = "via [$symbol]($style)"

[python]
format = "via [$symbol(\\($virtualenv\\) )]($style)"
symbol = " "

[quarto]
format = "via [$symbol]($style)"

[raku]
format = "via [$symbol]($style)"

[red]
format = "via [$symbol]($style)"

[rlang]
format = "via [$symbol]($style)"
symbol = "󰟔 "

[ruby]
format = "via [$symbol]($style)"
symbol = " "

[rust]
format = "via [$symbol]($style)"
symbol = "󱘗 "

[scala]
format = "via [$symbol]($style)"
symbol = " "

[shell]
disabled = true

[solidity]
format = "via [$symbol]($style)"

[status]
symbol = " "

[sudo]
disabled = true
symbol = "󰩪 "

[swift]
format = "via [$symbol]($style)"
symbol = " "

[typst]
format = "via [$symbol]($style)"

[vagrant]
format = "via [$symbol]($style)"

[vlang]
format = "via [$symbol]($style)"

[xmake]
format = "via [$symbol]($style)"
symbol = " "

[zig]
format = "via [$symbol]($style)"
symbol = " "

[os.symbols]
AlmaLinux = " "
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
RockyLinux = " "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
