[general]
import = ["themes/tokyonight_night.toml"]

[cursor.style]
shape = "Block"

[cursor.vi_mode_style]
shape = "Block"

[font]
size = 14

[font.normal]
family = "Fira Code Nerd Font"

[window]
dynamic_padding = true
opacity = 0.9

[window.dimensions]
columns = 128
lines = 32

[window.padding]
x = 8
y = 8
